### ISSUE TITLE
Original photo resolution

### ISSUE THREAD

**Issue by GrossGhost** [MastaBaba/LoremFlickr-2#6]
How i can get photo in original resolution?

**Comment by MastaBaba** [comment]
The LoremFlickr webservice limits the maximum size of an image that's returned. So, if you want to get the original resolution, you'll have to install the code on your own server and tweak the code a bit.

**Comment by GrossGhost** [comment]
Ok. Than how can i get photo with maximum size that LoremFlickr webservice can provide?

**Comment by MastaBaba** [comment]
The maximum size that the site returns should be an image of 1200x1200 pixels. So, for example:

https://loremflickr.com/1200/1200

**Comment by GrossGhost** [comment]
a lot of pictures are not available in size of 1200x1200, but for smaller resolution it works fine. Example:

it works fine:
https://loremflickr.com/700/700/sea?lock=1
https://loremflickr.com/320/320/sea?lock=1

it returns placeholder ( a photo of Tomboli ):
https://loremflickr.com/1200/1200/sea?lock=1
https://loremflickr.com/900/900/sea?lock=1

**Comment by MastaBaba** [comment]
It seems to me the lock parameter is causing an issue. Let me investigate.

**Comment by GrossGhost** [comment]
ok.thanx for help, and for yours webservice

**Comment by MastaBaba** [comment]
The problem was elsewhere: When asking for large images, the Flickr image that needs to be parsed can be very large. When it is, I set the code to refuse to process the large image. This, because my server, too often, crashes under heavy load.

That said, I've upped the accepted maximum size, for now. If my server doesn't survive, I'll probably lower it again.
